### ISSUE TITLE
Use guzzle/guzzle

### ISSUE THREAD

**Issue by fpletz** [mayflower/jira-vote#2]
On `composer install`, these warnings can be observed:

```
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/plugin-oauth is abandoned, you should avoid using it. Use guzzle/guzzle instead.
```

**Comment by Ma27** [comment]
I'm trying to repoduce it tonight

**Comment by Ma27** [comment]
the guzzle/* packages were retired in favor of one large guzzle/guzzle package which contains the whole legacy guzzle3 library.
But actually we need to refactor to guzzle4 (guzzlehttp/guzzle) since the guzzle3 is deprecated.
The next mayday I can join, I need to refactor that

**Comment by Ma27** [comment]
Guzzle5 is now in use, so this ticket is obsolete
